services:
  shared:
    image: ghcr.io/uncognic/shared:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - shared:/app/shared
    environment:
      FILE_SHARING_BASE_URL: https://files.example.com
      FILE_SHARING_STORAGE_PATH: /app/shared
      FILE_SHARING_MAX_FILE_SIZE_BYTES: 524288000
      FILE_SHARING_TOKENS_0: default
      # FILE_SHARING_TOKENS_1: another-token
      # FILE_SHARING_TOKENS_2: yet-another-token

volumes:
  shared:
